codecov:
  notify:
    after_n_builds: 14
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 25%
